### ISSUE TITLE
Compile errors on UE 5.1.1

### ISSUE THREAD

**Issue by rlabrecquefsg** [Ryan-DowlingSoka/RedTechArtTools#11]
Hey there, we just upgraded from v1.1.3-RedTechArtTools-win64 to main @ d42c52ed693de0ddb81e68cd3678babcf4a77c98 / 2023-03-01 for to prep for our 5.2 upgrade.

Here's a summary of the changes I had to make:

```
--- RedMultiLineEditableTextBox.cpp
@@ -38,13 +38,13 @@
 	MyEditableTextBlock = SNew(SMultiLineEditableTextBox)
 	.AllowContextMenu(AllowContextMenu)
 	.Style(&WidgetStyle)
 #if ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION <= 1 && ENGINE_PATCH_VERSION < 1
 	.TextStyle(&TextStyle);
 #endif
-#if ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION > 1
+#if ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 1
 	.IsReadOnly(GetIsReadOnly())
 #else
 	.IsReadOnly(bIsReadOnly)
 #endif
 //		.MinDesiredWidth(MinimumDesiredWidth)
 //		.Padding(Padding)

```

```
--- RedEditorIconWidget.cpp
@@ -21,13 +21,14 @@
 // SOFTWARE.
 
 #include "RedEditorIconWidget.h"
 
 #include "Brushes/SlateImageBrush.h"
 #include "Components/Image.h"
-
+#include "HAL/FileManager.h"
+#include "Launch/Resources/Version.h"
 
 void URedEditorIconWidget::SynchronizeProperties()
 {
 	Super::SynchronizeProperties();
 
 #if ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION > 1
```

I suspect there's a bunch more places where `#include "Launch/Resources/Version.h"` is necessary due to unity builds.

**Comment by Ryan-DowlingSoka** [comment]
Thanks for these. A pull request would also be appreciated, otherwise i will attempt to merge them when i get the chance. Be aware that if you are on 5.1, you will need to be on the 5.1 branch's content.

**Comment by Ryan-DowlingSoka** [comment]
[7e927cf](https://github.com/Ryan-DowlingSoka/RedTechArtTools/commit/7e927cf61b88ea41773015eeeea7315bfe0d5526)
