### ISSUE TITLE
The Readme link on the latest release goes to a 404 page

### ISSUE THREAD

**Issue by Qwigs** [Ryan-DowlingSoka/RedTechArtTools#7]
https://github.com/Ryan-DowlingSoka/RedTechArtTools/releases/tag/v1.1.3

Is https://github.com/Ryan-DowlingSoka/RedTechArtTools/blob/v1.1.3/github.com/Ryan-DowlingSoka/RedTechArtTools/readme.md
Should probably be https://github.com/Ryan-DowlingSoka/RedTechArtTools/blob/main/README.md

**Comment by Ryan-DowlingSoka** [comment]
Thanks! Good find.

Close, but the actual desired address is: [https://github.com/Ryan-DowlingSoka/RedTechArtTools/blob/v1.1.3/README.md](https://github.com/Ryan-DowlingSoka/RedTechArtTools/blob/v1.1.3/README.md) because it is best if the releases are linked to the readme from that same release.
