### ISSUE TITLE
Plugin compilation failed

### ISSUE THREAD

**Issue by NihilisticLotus** [Ryan-DowlingSoka/RedTechArtTools#9]
I failed to compile the plugin using ue5.1.1，Choosing to open directly and cmd command compilation will fail.
I compiled the 5.1 branch version in branches

`C:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles>RunUAT.bat BuildPlugin -plugin="B:\UE5_Project\UE5.1\NB\Plugins\RedTechArtTools\RedTechArtTools.uplugin" -package="D:\EV\RedTechArtTools"
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -plugin=B:\UE5_Project\UE5.1\NB\Plugins\RedTechArtTools\RedTechArtTools.uplugin -package=D:\EV\RedTechArtTools
Initializing script modules...
Total script module initialization time: 0.14 s.
Executing commands...
Copying 70 file(s) using max 64 thread(s)
Reading plugin from D:\EV\RedTechArtTools\HostProject\Plugins\RedTechArtTools\RedTechArtTools.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.1\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.1\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project=D:\EV\RedTechArtTools\HostProject\HostProject.uproject -plugin=D:\EV\RedTechArtTools\HostProject\Plugins\RedTechArtTools\RedTechArtTools.uplugin -iwyu -noubtmakefiles -manifest=D:\EV\RedTechArtTools\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml -nohotreload -log="C:\Users\76384\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.1\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\76384\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.1\UBT-UnrealEditor-Win64-Development.txt
Parsing headers for UnrealEditor
  Running Internal UnrealHeaderTool D:\EV\RedTechArtTools\HostProject\HostProject.uproject D:\EV\RedTechArtTools\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest -WarningsAsErrors -installed
D:\EV\RedTechArtTools\HostProject\Plugins\RedTechArtTools\Source\RedTechArtToolsEditor\Public\RedTechArtToolsBlueprintLibrary.h(40): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\EV\RedTechArtTools\HostProject\Plugins\RedTechArtTools\Source\RedTechArtToolsEditor\Public\RedTechArtToolsBlueprintLibrary.h(43): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
Total of 0 written
Took 4.0045206s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\76384\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.1\UBT-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 4s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
`
This is the result I compiled using cmd command

**Comment by Ryan-DowlingSoka** [comment]
This should be resolved. I fixed some header issues and some sets of missing categories. #12
